on: push
name: Push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -O https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip
          unzip packer_1.5.4_linux_amd64.zip
          ./packer build -only docker -var github_feed_token="${GITHUB_TOKEN}" images/linux/ubuntu1804.json
